export const SIMULATION_TICK_RATE = 20;
export const TICK_INTERVAL_MS = 1000 / SIMULATION_TICK_RATE;
export const MAX_CATCH_UP_TICKS = SIMULATION_TICK_RATE;
export const TICK_DURATION_WARN_MS = TICK_INTERVAL_MS * 0.9;
export const DRIFT_WARN_MS = TICK_INTERVAL_MS * 2;
